Locate python executable

diff --git a/bin/list_zones b/bin/list_zones
--- a/bin/list_zones
+++ b/bin/list_zones
@@ -36,7 +36,15 @@ fi
     fi
 }
 
-python $LIST -z $ZONE
+PYTHON_EXE=`type -p python`
+[ "${PYTHON_EXE}" ] || PYTHON_EXE=`type -p python3`
+
+[ "${PYTHON_EXE}" ] || {
+    echo "Could not locate python executable. Exiting."
+    exit 1
+}
+
+${PYTHON_EXE} $LIST -z $ZONE
 
 echo ""
 echo "Your configured zone groupings:"
diff --git a/bin/play_rp b/bin/play_rp
--- a/bin/play_rp
+++ b/bin/play_rp
@@ -22,4 +22,12 @@ else
     . ${ROONCONF}
 fi
 
-python $PLAY -z "$ROON_ZONE"
+PYTHON_EXE=`type -p python`
+[ "${PYTHON_EXE}" ] || PYTHON_EXE=`type -p python3`
+
+[ "${PYTHON_EXE}" ] || {
+    echo "Could not locate python executable. Exiting."
+    exit 1
+}
+
+${PYTHON_EXE} $PLAY -z "$ROON_ZONE"
diff --git a/bin/set_zone b/bin/set_zone
--- a/bin/set_zone
+++ b/bin/set_zone
@@ -17,32 +17,32 @@ cd ${ROONAPI}
     exit 1
 }
 MY_ZONE="$*"
-ZONE=`python $SCRIPT -c "verify" -z "$MY_ZONE"`
+
+PYTHON_EXE=`type -p python`
+[ "${PYTHON_EXE}" ] || PYTHON_EXE=`type -p python3`
+
+[ "${PYTHON_EXE}" ] || {
+    echo "Could not locate python executable. Exiting."
+    exit 1
+}
+
+ZONE=`${PYTHON_EXE} $SCRIPT -c "verify" -z "$MY_ZONE"`
 [ "$ZONE" ] || {
     echo "No zone matching $MY_ZONE"
     exit 1
 }
 
-# Locate Python user base
-USERSITE=`python -m site --user-site`
-# First check the Python user site dir
-if [ -d $USERSITE/roonapi ]
-then
-    PYTHONUSERBASE=`echo $USERSITE | awk -F "/lib/" ' { print $1 } '`
-else
-    # Check the global site directories
-    SITES=($(python -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
-    for site in ${SITES[@]}
-    do
-        site=`echo $site | sed -e "s/\'//g"`
-        [ -d "${site}/roonapi" ] && {
-            PYTHONUSERBASE=`echo ${site} | awk -F "/lib/" ' { print $1 } '`
-            break
-        }
-    done
-fi
-
-[ "$PYTHONUSERBASE" ] || PYTHONUSERBASE="$HOME/Python3"
+# Check the global site directories
+PYTHONUSERBASE=
+SITES=($(${PYTHON_EXE} -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
+for site in ${SITES[@]}
+do
+    site=`echo $site | sed -e "s/\'//g"`
+    [ -d "${site}/roonapi" ] && {
+        PYTHONUSERBASE=`echo ${site} | awk -F "/lib/" ' { print $1 } '`
+        break
+    }
+done
 
 if [ -f $ROONCONF ]
 then
@@ -50,10 +50,14 @@ then
     echo "ROON_ZONE=\"$ZONE\"" >> /tmp/roonconf$$
     cp /tmp/roonconf$$ $ROONCONF
     rm -f /tmp/roonconf$$
-    grep PYTHONUSERBASE $ROONCONF > /dev/null || {
+    [ "$PYTHONUSERBASE" ] && {
+      grep PYTHONUSERBASE $ROONCONF > /dev/null || {
         echo "export PYTHONUSERBASE=$PYTHONUSERBASE" >> $ROONCONF
+      }
     }
 else
     echo "ROON_ZONE=\"$ZONE\"" > $ROONCONF
-    echo "export PYTHONUSERBASE=$PYTHONUSERBASE" >> $ROONCONF
+    [ "$PYTHONUSERBASE" ] && {
+      echo "export PYTHONUSERBASE=$PYTHONUSERBASE" >> $ROONCONF
+    }
 fi
diff --git a/bin/set_zone_group b/bin/set_zone_group
--- a/bin/set_zone_group
+++ b/bin/set_zone_group
@@ -49,4 +49,12 @@ else
     . ${ROONCONF}
 fi
 
-python $SCRIPT -c "$ZONE_COMMAND" -z "$ROON_ZONE_GROUP"
+PYTHON_EXE=`type -p python`
+[ "${PYTHON_EXE}" ] || PYTHON_EXE=`type -p python3`
+
+[ "${PYTHON_EXE}" ] || {
+    echo "Could not locate python executable. Exiting."
+    exit 1
+}
+
+${PYTHON_EXE} $SCRIPT -c "$ZONE_COMMAND" -z "$ROON_ZONE_GROUP"
diff --git a/bin/zone_command b/bin/zone_command
--- a/bin/zone_command
+++ b/bin/zone_command
@@ -35,4 +35,12 @@ while getopts "c:z:" flag; do
     esac
 done
 
-python $SCRIPT -c "$COMMAND" -z "$ROON_ZONE"
+PYTHON_EXE=`type -p python`
+[ "${PYTHON_EXE}" ] || PYTHON_EXE=`type -p python3`
+
+[ "${PYTHON_EXE}" ] || {
+    echo "Could not locate python executable. Exiting."
+    exit 1
+}
+
+${PYTHON_EXE} $SCRIPT -c "$COMMAND" -z "$ROON_ZONE"
diff --git a/macInstall b/macInstall
--- a/macInstall
+++ b/macInstall
@@ -47,26 +47,26 @@ cp ${ROONETC}/roon_api.ini ${ROONETC}/roon_api.ini.orig
 cp /tmp/core$$ ${ROONETC}/roon_api.ini
 rm -f /tmp/core$$ /tmp/discover$$
 
-# Locate Python user base
-# USERSITE=`python -m site --user-site`
-# First check the Python user site dir
-# if [ -d $USERSITE/roonapi ]
-# then
-#     PYTHONUSERBASE=`echo $USERSITE | awk -F "/lib/" ' { print $1 } '`
-#     PYTHON_SITEDIR=`echo $USERSITE | awk -F "/site-packages" ' { print $1 } '`
-# else
-    # Check the global site directories
-    SITES=($(python -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
-    for site in ${SITES[@]}
-    do
-        site=`echo $site | sed -e "s/\'//g"`
-        [ -d "${site}/roonapi" ] && {
-            PYTHONUSERBASE=`echo ${site} | awk -F "/lib/" ' { print $1 } '`
-            PYTHON_SITEDIR=`echo ${site} | awk -F "/site-packages" ' { print $1 } '`
-            break
-        }
-    done
-# fi
+PYTHON_EXE=`type -p python`
+[ "${PYTHON_EXE}" ] || PYTHON_EXE=`type -p python3`
+
+[ "${PYTHON_EXE}" ] || {
+    echo "Could not locate python executable. Exiting."
+    exit 1
+}
+export PYTHON_EXE
+
+# Check the global site directories
+SITES=($(${PYTHON_EXE} -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
+for site in ${SITES[@]}
+do
+    site=`echo $site | sed -e "s/\'//g"`
+    [ -d "${site}/roonapi" ] && {
+        PYTHONUSERBASE=`echo ${site} | awk -F "/lib/" ' { print $1 } '`
+        PYTHON_SITEDIR=`echo ${site} | awk -F "/site-packages" ' { print $1 } '`
+        break
+    }
+done
 
 if [ "${PYTHONUSERBASE}" ]
 then
diff --git a/macUninstall b/macUninstall
--- a/macUninstall
+++ b/macUninstall
@@ -11,24 +11,25 @@ do
 done
 rm -rf ${ROON}
 
-# Locate Python user base
-# USERSITE=`python -m site --user-site`
+PYTHON_EXE=`type -p python`
+[ "${PYTHON_EXE}" ] || PYTHON_EXE=`type -p python3`
+
+[ "${PYTHON_EXE}" ] || {
+    echo "Could not locate python executable. Exiting."
+    exit 1
+}
+export PYTHON_EXE
+
 ROON_SITE_DIR=
-# First check the Python user site dir
-# if [ -d $USERSITE/roonapi ]
-# then
-#     ROON_SITE_DIR=${USERSITE}/roonapi
-# else
-    # Check the global site directories
-    SITES=($(python -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
-    for site in ${SITES[@]}
-    do
-        [ -d ${site}/roonapi ] && {
-            ROON_SITE_DIR=${site}/roonapi
-            break
-        }
-    done
-# fi
+# Check the global site directories
+SITES=($(${PYTHON_EXE} -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
+for site in ${SITES[@]}
+do
+    [ -d ${site}/roonapi ] && {
+        ROON_SITE_DIR=${site}/roonapi
+        break
+    }
+done
 
 rm -f $ROONCONF
 
diff --git a/patches/mkpatch-roonapi b/patches/mkpatch-roonapi
--- a/patches/mkpatch-roonapi
+++ b/patches/mkpatch-roonapi
@@ -3,25 +3,28 @@
 PYDIR=$HOME/.pyenv/versions/3.9.4/lib/python3.9
 USERSITE=$PYDIR/site-packages
 
+PYTHON_EXE=`type -p python`
+[ "${PYTHON_EXE}" ] || PYTHON_EXE=`type -p python3`
+
+[ "${PYTHON_EXE}" ] || {
+    echo "Could not locate python executable. Exiting."
+    exit 1
+}
+
+export PYTHON_EXE
+
 [ -d $USERSITE/roonapi ] || {
-    # First check the Python User Site directory
-    USERSITE=`python -m site --user-site`
-    if [ -d $USERSITE/roonapi ]
-    then
-        PYDIR=`echo $USERSITE | awk -F "/site-packages/" ' { print $1 } '`
-    else
-        # Next check Python's global directories
-        SITES=($(python -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
-        for site in ${SITES[@]}
-        do
-            site=`echo $site | sed -e "s/\'//g"`
-            [ -d "${site}/roonapi" ] && {
-                PYDIR=`echo ${site} | awk -F "/site-packages/" ' { print $1 } '`
-                USERSITE=$PYDIR/site-packages
-                break
-            }
-        done
-    fi
+    # Next check Python's global directories
+    SITES=($(${PYTHON_EXE} -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
+    for site in ${SITES[@]}
+    do
+        site=`echo $site | sed -e "s/\'//g"`
+        [ -d "${site}/roonapi" ] && {
+            PYDIR=`echo ${site} | awk -F "/site-packages/" ' { print $1 } '`
+            USERSITE=$PYDIR/site-packages
+            break
+        }
+    done
     [ -d $USERSITE/roonapi ] || {
         echo "Roon API Python module not found. Exiting."
         exit 1
