Add support for unattended install and check Python virtual env on startup

diff --git a/bin/roon b/bin/roon
--- a/bin/roon
+++ b/bin/roon
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # roon - frontend script to issue commands to Roon via the Python Roon API
 #
@@ -59,7 +59,7 @@ usage() {
       rich "    [cyan]-F[/] [yellow]\[from zone][/] [cyan]-f[/] [yellow]\[on|onlog|off|status][/] [cyan]-g[/] [yellow]genre[/] [cyan]-G[/] [yellow]zone_group[/] [cyan]-i[/]" --print
       rich "    [cyan]-I -l[/] [yellow]\[albums|artists|artalbums|albtracks|arttracks|composers|comalbums|[/]" --print
       rich "        [yellow]genres|genalbums|genartists|playlists|playtracks|tags|zones][/]" --print
-      rich "    [cyan]-c[/] [yellow]\[group|ungroup|play|play_all|pause|pause_all|stop|stop_all|[/]" --print
+      rich "    [cyan]-c[/] [yellow]\[discover|group|ungroup|play|play_all|pause|pause_all|stop|stop_all|[/]" --print
       rich "        [yellow]next|previous|shuffle|unshuffle|repeat|unrepeat|mute|mute_all][/]" --print
       rich "    [cyan]-s[/] [yellow]search[/] [cyan]-p[/] [yellow]playlist[/] [cyan]-T[/] [yellow]track[/] [cyan]-t[/] [yellow]tag[/] [cyan]-z[/] [yellow]zone[/] [cyan]-L[/] [cyan]-S[/] [cyan]-r[/] [yellow]radio[/]" --print
       rich "    [cyan]-X[/] [yellow]ex_album[/] [cyan]-x[/] [yellow]ex_artist[/] [cyan]\[-EuU][/]" --print
@@ -97,7 +97,7 @@ usage() {
       rich "    [cyan]-T[/] [yellow]track[/] specifies a track to play" --print
       rich "    [cyan]-t[/] [yellow]tag[/] selects an tag to play" --print
       rich "    [cyan]-z[/] [yellow]zone[/] selects the Roon Zone in which to play" --print
-      rich "    [cyan]-c[/] [yellow]\[group|ungroup|play|play_all|pause|pause_all|playpause|stop|stop_all|[/]" --print
+      rich "    [cyan]-c[/] [yellow]\[discover|group|ungroup|play|play_all|pause|pause_all|playpause|stop|stop_all|[/]" --print
       rich "        [yellow]next|previous|shuffle|unshuffle|repeat|unrepeat|mute|mute_all][/]" --print
       rich "            issues the command in the selected zone" --print
       rich "            '[italic green]roon -c mute[/]' toggles the zone's muted or unmuted state" --print
@@ -131,7 +131,7 @@ usage() {
       printf "\n\t-F [from zone] -f [on|onlog|off|status] -g genre -G zone_group -i"
       printf "\n\t-I -l [albums|artists|artalbums|albtracks|arttracks|composers|comalbums|"
       printf "\n\t    genres|genalbums|genartists|playlists|playtracks|tags|zones]"
-      printf "\n\t-c [group|ungroup|play|play_all|pause|pause_all|stop|stop_all|"
+      printf "\n\t-c [discover|group|ungroup|play|play_all|pause|pause_all|stop|stop_all|"
       printf "\n\t    next|previous|shuffle|unshuffle|repeat|unrepeat|mute|mute_all]"
       printf "\n\t-s search -p playlist -T track -t tag -z zone -L -S -r radio"
       printf "\n\t-X ex_album -x ex_artist [-EuU]"
@@ -168,7 +168,7 @@ usage() {
       printf "\n\t-T track specifies a track to play"
       printf "\n\t-t tag selects an tag to play"
       printf "\n\t-z zone selects the Roon Zone in which to play"
-      printf "\n\t-c [group|ungroup|play|play_all|pause|pause_all|playpause|stop|stop_all|"
+      printf "\n\t-c [discover|group|ungroup|play|play_all|pause|pause_all|playpause|stop|stop_all|"
       printf "\n\t    next|previous|shuffle|unshuffle|repeat|unrepeat|mute|mute_all]"
       printf "\n\t        issues the command in the selected zone"
       printf "\n\t        'mute' toggles the zone's muted or unmuted state"
@@ -799,6 +799,13 @@ ROONCONF=${ROONETC}/pyroonconf
 LOCAL=false
 BOLD=$(tput bold 2>/dev/null)
 NORMAL=$(tput sgr0 2>/dev/null)
+
+# Check Python virtual environment
+[ -e ${ROON}/venv/bin/python3 ] || {
+  printf "\nRepairing RoonCommandLine Python virtual environment ..."
+  [ -x ${ROONETC}/upgrade-venv ] && ${ROONETC}/upgrade-venv
+  printf " done\n"
+}
 
 [ -f ${ROON}/venv/bin/activate ] && source ${ROON}/venv/bin/activate
 [ -x ${ROON}/venv/bin/python ] && export PYTHON=${ROON}/venv/bin/python
@@ -2167,6 +2174,16 @@ while getopts A:a:bBc:C:dD:f:F:g:G:hHiImnNOp:T:t:z:l:s:LSr:v:x:X:EuU flag; do
       ;;
   esac
 done
+
+[ "${comm}" == "discover" ] && {
+  if [ -x ${ROONETC}/discover ]; then
+    ${ROONETC}/discover
+    exit 0
+  else
+    echo "ERROR: ${ROONETC}/discover not found or not executable. Reinstall."
+    exit 1
+  fi
+}
 
 [ "${inst_roon_gui}" ] && {
   [ -x ${ROON}/etc/install-roon-gui ] && ${ROON}/etc/install-roon-gui
