Add list album tracks, use fzf to select media and list media, add functions file

diff --git a/bin/roontui b/bin/roontui
--- a/bin/roontui
+++ b/bin/roontui
@@ -19,10 +19,11 @@
 #   -l, --log <LOG>           Path to the log file [default: ~/.config/roon-tui/roon-tui.log]
 #   -v, --verbose             Enable verbose logging to file
 #   -u, --no-unicode-symbols  Disable the use of Unicode symbols
-#   -U, --upgrade             Upgrade roon-tui if a newer version is available
+#   -U, --upgrade             Upgrade roon-tui if a newer version is available and exit
 #   -h, --help                Print help
 #   -V, --version             Print version
 
+ROON="/usr/local/Roon"
 TUI_CONFDIR="${HOME}/.config/roon-tui"
 TUI_CONF="${TUI_CONFDIR}/config.json"
 TUI_LOG="${TUI_CONFDIR}/roon-tui.log"
@@ -49,7 +50,7 @@ usage() {
   printf "\n  -l, --log <LOG>           Path to the log file"
   printf "\n  -v, --verbose             Enable verbose logging to file"
   printf "\n  -u, --no-unicode-symbols  Disable the use of Unicode symbols"
-  printf "\n  -U, --upgrade             Upgrade roon-tui if a newer version is available"
+  printf "\n  -U, --upgrade             Upgrade roon-tui if a newer version is available and exit"
   printf "\n  -h, --help                Print help"
   printf "\n  -V, --version             Print version\n"
   printf "\nDefaults:"
@@ -57,6 +58,40 @@ usage() {
   printf "\n  Configuration location:   ${TUI_CONF}"
   printf "\n  Log file location:        ${TUI_LOG}\n\n"
   exit 1
+}
+
+# check_version release_version install_version
+check_version() {
+  release_version="$1"
+  install_version="$2"
+
+  release_major=$(echo ${release_version} | awk -F '.' '{ print $1 }')
+  release_midde=$(echo ${release_version} | awk -F '.' '{ print $2 }')
+  release_minor=$(echo ${release_version} | awk -F '.' '{ print $3 }')
+  [ "${release_major}" ] || release_major=0
+  [ "${release_midde}" ] || release_midde=0
+  [ "${release_minor}" ] || release_minor=0
+
+  install_major=$(echo ${install_version} | awk -F '.' '{ print $1 }')
+  install_midde=$(echo ${install_version} | awk -F '.' '{ print $2 }')
+  install_minor=$(echo ${install_version} | awk -F '.' '{ print $3 }')
+  [ "${install_major}" ] || install_major=0
+  [ "${install_midde}" ] || install_midde=0
+  [ "${install_minor}" ] || install_minor=0
+
+  if [ ${release_major} -gt ${install_major} ]; then
+    echo "${release_version}"
+  else
+    if [ ${release_midde} -gt ${install_midde} ]; then
+      echo "${release_version}"
+    else
+      if [ ${release_minor} -gt ${install_minor} ]; then
+        echo "${release_version}"
+      else
+        echo ""
+      fi
+    fi
+  fi
 }
 
 IP_OPT=
@@ -108,8 +143,24 @@ while [[ $1 ]]; do
       shift
       ;;
     -U | --upgrade)
-      ROON="/usr/local/Roon"
-      [ -x ${ROON}/etc/install-roon-tui ] && ${ROON}/etc/install-roon-tui
+      if [ -x ${ROON}/etc/install-roon-tui ]; then
+        if [ "${TUI_BIN}" ]; then
+          tui_release=$(${ROON}/etc/install-roon-tui version)
+          tui_install=$(${TUI_BIN} --version | awk '{ print $2 }')
+          update_tui=$(check_version "${tui_release}" "${tui_install}")
+          if [ "${update_tui}" ]; then
+            ${ROON}/etc/install-roon-tui
+          else
+            printf "\nInstalled version of roon-tui, ${tui_install}, is current ✨ 🌟 ✨\n\n"
+          fi
+        else
+          ${ROON}/etc/install-roon-tui
+        fi
+        exit 0
+      else
+        printf "\n${ROON}/etc/install-roon-tui not found. Upgrade RoonCommandLine.\n\n"
+        exit 1
+      fi
       shift
       ;;
     -h | --help)
