Install in /usr/local/Roon/ and use global Python site packages. Add Debian format packaging, major reorg, bump major version to 2

diff --git a/bin/set_zone b/bin/set_zone
--- a/bin/set_zone
+++ b/bin/set_zone
@@ -1,14 +1,15 @@
 #!/bin/bash
 
-ROONCONF=$HOME/.pyroonconf
-ROON=$HOME/RoonCommandLine
+ROON=/usr/local/Roon
+ROONAPI=${ROON}/api
+ROONCONF=${ROON}/etc/pyroonconf
 SCRIPT="zone_command.py"
 
-[ -f ${ROON}/${SCRIPT} ] || {
-    echo "Roon Command Line scripts not installed. Missing $ROON/$SCRIPT"
+[ -f ${ROONAPI}/${SCRIPT} ] || {
+    echo "Roon Command Line scripts not installed. Missing ${ROONAPI}/$SCRIPT"
     exit 1
 }
-cd ${ROON}
+cd ${ROONAPI}
 
 # Verify this is a valid zone name
 [ "$1" ] || {
diff --git a/bin/set_zone_group b/bin/set_zone_group
--- a/bin/set_zone_group
+++ b/bin/set_zone_group
@@ -1,14 +1,16 @@
 #!/bin/bash
 
-ROONCONF=$HOME/.pyroonconf
-ROON=$HOME/RoonCommandLine
+ROON=/usr/local/Roon
+ROONAPI=${ROON}/api
+ROONETC=${ROON}/etc
+ROONCONF=${ROONETC}/pyroonconf
 SCRIPT="zone_group.py"
 
-[ -f ${ROON}/${SCRIPT} ] || {
-    echo "Roon Command Line scripts not installed. Missing $ROON/$SCRIPT"
+[ -f ${ROONAPI}/${SCRIPT} ] || {
+    echo "Roon Command Line scripts not installed. Missing $ROONAPI/$SCRIPT"
     exit 1
 }
-cd ${ROON}
+cd ${ROONAPI}
 
 # Verify this is a valid zone grouping command
 [ "$1" ] || {
@@ -28,7 +30,7 @@ ZONE_COMMAND="$1"
 }
 ROON_ZONE_GROUP="Group_$2"
 found_group=
-for gn in `grep ^Group_ $ROON/roon_api.ini | awk -F '=' ' { print $1 } '`
+for gn in `grep ^Group_ ${ROONETC}/roon_api.ini | awk -F '=' ' { print $1 } '`
 do
     gn="$(echo -e "${gn}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
     [ "$ROON_ZONE_GROUP" == "$gn" ] && found_group=1
@@ -42,7 +44,7 @@ if [ -f ${ROONCONF} ]
 then
     . ${ROONCONF}
 else
-    DEFZONE=`grep ^DefaultZone $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
+    DEFZONE=`grep ^DefaultZone ${ROONETC}/roon_api.ini | awk -F '=' ' { print $2 } '`
     set_zone $DEFZONE
     . ${ROONCONF}
 fi
