Install/Uninstall now supports RPM, Debian, and Mac

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -8,7 +8,7 @@
 # You should probably be running a more recent version of apt
 # On these early versions, install with the following:
 #
-# sudo dpkg -i "${DEB}"
+# sudo dpkg -i "${PKG}"
 # sudo apt-get install -f
 
 SRC_NAME="RoonCommandLine"
@@ -16,7 +16,6 @@ PKG_NAMES="RoonCommandLine"
 APT_NAMES="rooncommandline"
 SRC="${HOME}/src"
 
-PKG_INSTALLED=
 PKG_AVAILABLE=
 PKG_SELECTED=
 
@@ -28,14 +27,15 @@ PKG_SELECTED=
 
 . "${SRC}/${SRC_NAME}/VERSION"
 PKG_VER=${VERSION}
+PKG_REL=${RELEASE}
 
 get_available_packages() {
-  for debs in ${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.deb
+  for pkgs in ${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.${SUF}
   do
-    [ "${debs}" == "${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.deb" ] || {
-      for pkg in ${debs}
+    [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.${SUF}" ] || {
+      for pkg in ${pkgs}
       do
-        pkgname=`basename ${pkg} | sed -e "s/_${PKG_VER}.deb//"` 
+        pkgname=`basename ${pkg} | sed -e "s/_${PKG_VER}-${PKG_REL}.${SUF}//"` 
         PKG_AVAILABLE="${PKG_AVAILABLE} ${pkgname}"
       done
     }
@@ -71,7 +71,20 @@ if [ "$plat" == "Darwin" ]
 then
   ./macInstall
 else
+  debian=
+  have_apt=`type -p apt`
+  have_dpkg=`type -p dpkg`
+  have_rpm=`type -p rpm`
+  have_yum=`type -p yum`
+  [ -f /etc/os-release ] && . /etc/os-release
+  [ "${ID_LIKE}" == "debian" ] && debian=1
+  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
+
+  SUF=deb
+  [ "${debian}" ] || SUF=rpm
+
   get_available_packages
+
   [ "$PKG_AVAILABLE}" ] || {
     echo "No packages for version ${PKG_VER} are currently available. Exiting."
     exit 1
@@ -83,15 +96,6 @@ else
     then
       shift
       PKG_NAMES="$*"
-      [ "${PKG_INSTALLED}" ] && {
-        echo "Currently installed RoonCommandLine packages:"
-        echo ""
-        for instpkg in ${PKG_INSTALLED}
-        do
-          echo "$instpkg"
-        done
-        echo ""
-      }
       [ "${PKG_AVAILABLE}" ] && {
         echo "Currently available RoonCommandLine packages:"
         echo ""
@@ -136,21 +140,46 @@ else
 
   for PKG_NAME in ${PKG_NAMES}
   do
-    DEB="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}.deb"
-    [ -f "${DEB}" ] || {
-      echo "${PKG_NAME}_${PKG_VER}.deb not found."
-      for debs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.deb
+    PKG="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF}"
+    [ -f "${PKG}" ] || {
+      echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF} not found."
+      for pkgs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}
       do
-        [ "${debs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.deb" ] || {
+        [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
           echo "Found existing packages:"
-          echo "${debs}"
+          echo "${pkgs}"
         }
       done
       echo ""
       continue
     }
 
-    echo "Installing ${DEB}"
-    sudo apt install "${DEB}"
+    echo "Installing ${PKG}"
+    if [ "${debian}" ]
+    then
+      if [ "${have_apt}" ]
+      then
+        sudo apt install "${PKG}"
+      else
+        if [ "${have_dpkg}" ]
+        then
+          sudo dpkg -i "${PKG}"
+        else
+          echo "Cannot locate either apt or dpkg to install. Skipping."
+        fi
+      fi
+    else
+      if [ "${have_yum}" ]
+      then
+        sudo yum localinstall "${PKG}"
+      else
+        if [ "${have_rpm}" ]
+        then
+          sudo rpm -i "${PKG}"
+        else
+          echo "Cannot locate either yum or rpm to install. Skipping."
+        fi
+      fi
+    fi
   done
 fi
